# setup_postgres.ps1 - provision the bundled PostgreSQL for a native install.
#
# The Windows counterpart to what docker-compose.yml's postgres_primary
# service did: create a data directory, lock the server to loopback, and
# start it under a name something else can depend on. The MSI calls this
# before cmd/bootstrap, which needs a reachable database to migrate.
#
# PostgreSQL ships as a binaries-only zip (bin/, lib/, share/) with no
# installer, which is what makes bundling it viable: the whole server is a
# directory the MSI lays down, and this script turns that directory into a
# running instance.
#
# Idempotent, because the MSI runs it again on every upgrade. An existing
# data directory is left exactly as it is, and an already-registered service
# is started rather than re-created. Re-initialising would destroy the
# database.
#
# ASCII only, deliberately: Windows PowerShell 5.1 reads a .ps1 as ANSI
# unless it carries a UTF-8 BOM, so a stray em-dash in a comment becomes a
# parse error rather than a typo. Keeping to ASCII avoids depending on the
# BOM surviving every editor and copy that touches this file.
#
# Usage (from an elevated prompt, as the MSI runs it):
#   .\setup_postgres.ps1 -InstallDir 'C:\Program Files\ISP BSS' -SuperuserPassword '<generated>'
#
# Verification-only run, no service registration, on a spare port:
#   .\setup_postgres.ps1 -InstallDir D:\test -SuperuserPassword pw -Port 15433 -SkipService

[CmdletBinding()]
param(
    # Root of the install. Expects pgsql\bin beneath it, and creates
    # pgdata\ and logs\ alongside.
    [Parameter(Mandatory = $true)][string]$InstallDir,

    # Password for the postgres superuser. Generated by the installer and
    # used only by cmd/bootstrap; the services connect as bss_app instead.
    [Parameter(Mandatory = $true)][string]$SuperuserPassword,

    [int]$Port = 5432,
    [string]$DatabaseName = 'isp_bss_oss',
    [string]$ServiceName = 'ISPBSSPostgres',

    # Skip Windows service registration and just run the server. For
    # verification runs that must not touch machine state.
    [switch]$SkipService
)

$ErrorActionPreference = 'Stop'

$PgBin   = Join-Path $InstallDir 'pgsql\bin'
$PgData  = Join-Path $InstallDir 'pgdata'
$LogDir  = Join-Path $InstallDir 'logs'
$LogFile = Join-Path $LogDir 'postgres.log'

$InitDb    = Join-Path $PgBin 'initdb.exe'
$PgCtl     = Join-Path $PgBin 'pg_ctl.exe'
$PgIsReady = Join-Path $PgBin 'pg_isready.exe'
$CreateDb  = Join-Path $PgBin 'createdb.exe'
$Psql      = Join-Path $PgBin 'psql.exe'

foreach ($exe in @($InitDb, $PgCtl, $PgIsReady, $CreateDb, $Psql)) {
    if (-not (Test-Path $exe)) {
        throw "missing $exe - the bundled PostgreSQL is not laid out as expected under $PgBin"
    }
}

New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

# ---- Initialise the cluster -------------------------------------------------
#
# PG_VERSION is initdb's own marker for a populated data directory, so its
# presence is the check rather than the directory existing (the MSI may have
# created an empty one).
if (Test-Path (Join-Path $PgData 'PG_VERSION')) {
    Write-Host "setup_postgres: existing cluster at $PgData, leaving it alone"
} else {
    Write-Host "setup_postgres: initialising a new cluster at $PgData"
    New-Item -ItemType Directory -Force -Path $PgData | Out-Null

    # initdb reads the password from a file rather than an argument, which
    # keeps it out of the process list other users can read.
    $pwFile = Join-Path $env:TEMP ("pgpw-" + [guid]::NewGuid().ToString() + ".txt")
    try {
        # ASCII with no BOM: initdb reads this file literally, and a UTF-8
        # BOM would become part of the password.
        [System.IO.File]::WriteAllText($pwFile, $SuperuserPassword, [System.Text.Encoding]::ASCII)

        # scram-sha-256 for both local and host connections rather than the
        # 'trust' initdb defaults to on Windows, which would let any local
        # process connect as the superuser without a password.
        & $InitDb --pgdata=$PgData --username=postgres --pwfile=$pwFile `
            --encoding=UTF8 --locale=C `
            --auth-local=scram-sha-256 --auth-host=scram-sha-256 | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "initdb failed with exit code $LASTEXITCODE" }
    } finally {
        if (Test-Path $pwFile) { Remove-Item $pwFile -Force }
    }

    # Loopback only. This database backs a single-machine install and has no
    # reason to accept a connection from the network; leaving it open would
    # expose it to the same LAN the RADIUS clients sit on.
    $conf = Join-Path $PgData 'postgresql.conf'
    Add-Content -Path $conf -Encoding utf8 -Value @"

# Set by setup_postgres.ps1 for the native single-machine install.
listen_addresses = 'localhost'
port = $Port
"@
    Write-Host "setup_postgres: cluster initialised, listening on localhost:$Port only"
}

# ---- Register and start -----------------------------------------------------

# The port is not passed to pg_ctl here. It was written into
# postgresql.conf at initdb time, which keeps one source of truth: passing
# -o "-p $Port" as well would let a later run start the server on a port
# its own config disagrees with. It also avoids an argument-quoting trap,
# since the space inside "-p 5432" does not survive Start-Process's
# argument array intact.
# Already up? On an upgrade the database service is typically still
# running while the app services are stopped, and firing a start at a live
# server just produces a confusing "another server might be running" in the
# logs.
& $PgIsReady -h 127.0.0.1 -p $Port -U postgres | Out-Null
$alreadyRunning = ($LASTEXITCODE -eq 0)

if ($alreadyRunning) {
    Write-Host "setup_postgres: server already running on port $Port"
} elseif ($SkipService) {
    Write-Host "setup_postgres: -SkipService given, starting the server directly"
    # Launched without waiting on it, deliberately. pg_ctl returns as soon
    # as the server is up, but the postmaster it leaves behind is a child
    # of it, and both -Wait and a plain `& $PgCtl` wait on that whole tree
    # - so the script blocks for the life of the server on a command that
    # already succeeded. Readiness is established by the pg_isready loop
    # below instead, which is the thing actually worth waiting for.
    $outLog = Join-Path $LogDir 'pg_ctl-start.out'
    $errLog = Join-Path $LogDir 'pg_ctl-start.err'
    Start-Process -FilePath $PgCtl `
        -ArgumentList @('-D', $PgData, '-l', $LogFile, 'start') `
        -WindowStyle Hidden `
        -RedirectStandardOutput $outLog -RedirectStandardError $errLog | Out-Null
} else {
    $existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($null -eq $existing) {
        Write-Host "setup_postgres: registering the $ServiceName service"
        & $PgCtl register -N $ServiceName -D $PgData -S auto
        if ($LASTEXITCODE -ne 0) { throw "pg_ctl register failed with exit code $LASTEXITCODE" }
    } else {
        Write-Host "setup_postgres: $ServiceName already registered"
    }
    Start-Service -Name $ServiceName
}

# ---- Wait, then create the database -----------------------------------------
#
# Waited for rather than assumed: the service reports Running before the
# postmaster is accepting connections, and cmd/bootstrap runs immediately
# after this script.
$deadline = (Get-Date).AddSeconds(60)
do {
    & $PgIsReady -h 127.0.0.1 -p $Port -U postgres | Out-Null
    $ready = ($LASTEXITCODE -eq 0)
    if (-not $ready) { Start-Sleep -Milliseconds 500 }
} while (-not $ready -and (Get-Date) -lt $deadline)

if (-not $ready) {
    # This loop is the only thing establishing that startup worked (see the
    # note above on why pg_ctl is not waited on), so a timeout has to carry
    # the server's own reason rather than just the fact of the timeout.
    $tail = if (Test-Path $LogFile) { Get-Content $LogFile -Tail 20 | Out-String } else { '(no log written)' }
    throw "PostgreSQL did not start accepting connections within 60s.`n--- $LogFile ---`n$tail"
}
Write-Host "setup_postgres: server accepting connections on port $Port"

$env:PGPASSWORD = $SuperuserPassword
try {
    # Asked, not attempted. Letting createdb fail on an existing database
    # would be the natural way to express this, but under
    # $ErrorActionPreference='Stop' PowerShell 5.1 turns a native command's
    # stderr into a terminating NativeCommandError - so the ordinary
    # upgrade case would abort the installer. Querying first keeps the
    # error path meaning something went wrong.
    #
    # Not chained straight into .Trim(): on a fresh install the database
    # does not exist yet, the query returns zero rows, and psql then prints
    # nothing at all - which PowerShell captures as $null, not "". $null
    # has no .Trim() method, so the fresh-install branch (the common case)
    # threw "You cannot call a method on a null-valued expression" every
    # time, unconditionally. Missed the first time this existence check was
    # written because the follow-up test only re-ran the upgrade path
    # (database already exists, so $exists really is the string "1"),
    # never the first-install path this exact line breaks.
    $exists = & $Psql -h 127.0.0.1 -p $Port -U postgres -d postgres -tAc `
        "SELECT 1 FROM pg_database WHERE datname = '$DatabaseName'"
    if ($LASTEXITCODE -ne 0) { throw "could not query for database $DatabaseName" }
    if ($null -ne $exists) { $exists = $exists.Trim() }

    if ($exists -eq '1') {
        Write-Host "setup_postgres: database $DatabaseName already exists"
    } else {
        & $CreateDb -h 127.0.0.1 -p $Port -U postgres $DatabaseName
        if ($LASTEXITCODE -ne 0) { throw "createdb failed with exit code $LASTEXITCODE" }
        Write-Host "setup_postgres: created database $DatabaseName"
    }
} finally {
    Remove-Item Env:\PGPASSWORD -ErrorAction SilentlyContinue
}

Write-Host "setup_postgres: done - run bootstrap.exe next to migrate and generate secrets"
